version: '3.9'

services:

  asset-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: asset-management-service
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      app-network:


  app:
    image: quarkus/orders-microservice-jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://asset-db:5432/asset-management-service
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=admin
    depends_on:
      - asset-db
    volumes:
      - ./app:/usr/src/app
    networks:
      app-network:

networks:
  app-network: